// <auto-generated />
using System;
using EFC_WMP_Asset_Tracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC_WMP_Asset_Tracking.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240529202149_AddedSampleData")]
    partial class AddedSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFC_WMP_Asset_Tracking.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceUSD")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "ASUS ROG",
                            Currency = "SEK",
                            Model = "B550-F",
                            Office = "Sweden",
                            PriceUSD = 243m,
                            PurchaseDate = new DateOnly(2020, 11, 24),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "HP",
                            Currency = "USD",
                            Model = "14S-FQ1010NO",
                            Office = "USA",
                            PriceUSD = 679m,
                            PurchaseDate = new DateOnly(2022, 1, 30),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "HP",
                            Currency = "EUR",
                            Model = "Elitebook",
                            Office = "Greece",
                            PriceUSD = 2234m,
                            PurchaseDate = new DateOnly(2021, 8, 30),
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "HP",
                            Currency = "SEK",
                            Model = "Elitebook",
                            Office = "Sweden",
                            PriceUSD = 2234m,
                            PurchaseDate = new DateOnly(2020, 7, 30),
                            Type = "Computer"
                        });
                });

            modelBuilder.Entity("EFC_WMP_Asset_Tracking.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceUSD")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Brand = "Samsung",
                            Currency = "SEK",
                            Model = "S20 Plus",
                            Office = "Sweden",
                            PriceUSD = 1500m,
                            PurchaseDate = new DateOnly(2020, 9, 12),
                            Type = "Phone"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Sony Xperia",
                            Currency = "USD",
                            Model = "10 III",
                            Office = "USA",
                            PriceUSD = 800m,
                            PurchaseDate = new DateOnly(2020, 3, 6),
                            Type = "Phone"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Iphone",
                            Currency = "EUR",
                            Model = "10",
                            Office = "Greece",
                            PriceUSD = 951m,
                            PurchaseDate = new DateOnly(2018, 11, 25),
                            Type = "Phone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
